Traceback (most recent call last):
  File "/Users/filipepacheco/CascadeProjects/RentalPriceTrackerPerDay/main.py", line 8143, in get_vehicle_photo
    return Response(
UnboundLocalError: local variable 'Response' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/filipepacheco/CascadeProjects/RentalPriceTrackerPerDay/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/filipepacheco/CascadeProjects/RentalPriceTrackerPerDay/.venv/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/Users/filipepacheco/CascadeProjects/RentalPriceTrackerPerDay/.venv/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/Users/filipepacheco/CascadeProjects/RentalPriceTrackerPerDay/.venv/lib/python3.9/site-packages/starlette/middleware/sessions.py", line 85, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/Users/filipepacheco/CascadeProjects/RentalPriceTrackerPerDay/.venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/filipepacheco/CascadeProjects/RentalPriceTrackerPerDay/.venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/filipepacheco/CascadeProjects/RentalPriceTrackerPerDay/.venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/filipepacheco/CascadeProjects/RentalPriceTrackerPerDay/.venv/lib/python3.9/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/filipepacheco/CascadeProjects/RentalPriceTrackerPerDay/.venv/lib/python3.9/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/filipepacheco/CascadeProjects/RentalPriceTrackerPerDay/.venv/lib/python3.9/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/filipepacheco/CascadeProjects/RentalPriceTrackerPerDay/.venv/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/filipepacheco/CascadeProjects/RentalPriceTrackerPerDay/.venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/filipepacheco/CascadeProjects/RentalPriceTrackerPerDay/.venv/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/filipepacheco/CascadeProjects/RentalPriceTrackerPerDay/.venv/lib/python3.9/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/Users/filipepacheco/CascadeProjects/RentalPriceTrackerPerDay/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/Users/filipepacheco/CascadeProjects/RentalPriceTrackerPerDay/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/filipepacheco/CascadeProjects/RentalPriceTrackerPerDay/main.py", line 8157, in get_vehicle_photo
    return Response(
UnboundLocalError: local variable 'Response' referenced before assignment
